### ISSUE TITLE
Allow to limit the amount of workers 

### ISSUE THREAD

**Issue by dotansimha** [VincentBailly/yarn#36]
Since this change: https://github.com/VincentBailly/yarn/commit/d8c0712e80e5ef13013b75afaf144588f8aaa1a9 , this fork is using `os.cpus` to create workers. This might lead to an issue because of this: https://github.com/nodejs/node/issues/28762 (while running in a Docker environment). 

I created this PR to make it possible to override this configuration with an environment variable: https://github.com/VincentBailly/yarn/pull/35

**Comment by VincentBailly** [comment]
PR merged
