### ISSUE TITLE
The future of this fork

### ISSUE THREAD

**Issue by theprobugmaker** [VincentBailly/yarn#37]
I really like what you are doing improving Yarn v1. The community isn't happy with v2 and it would be really nice to have someone continuing this and making it better.
What are your intentions? Do you plan on changing the name and releasing it or something like that?

**Comment by VincentBailly** [comment]
Hi @zefexdeveloper, sorry for taking more than a month to answer.

The intentions for the future of this branch are unclear. This is a question many people ask so I would like to answer it but I am unable to do that at the moment.

The current state is that I accept contributions and the branch is released to the package called midgard-yarn.
